### ISSUE TITLE
docker: fullBlocks.bin.lck never removed

### ISSUE THREAD

**Issue by wildmolasses** [Great-Hill-Corporation/trueblocks-core#1012]
`docker-compose stop` stops the container but does not remove fullBlocks.bin.lck. 
More on `docker-compose stop`: https://docs.docker.com/engine/reference/commandline/stop/

One bandaid solution is to include `rm ~/.quickBlocks/cache/fullBlocks.bin.lck` in our entrypoint script.

**Comment by wildmolasses** [comment]
Is there a better way to run blockScrape? One idea is to set maxBlocks to say 10 but set the timeout to be 0 until getBlock reports we're caught up to the head of the chain.

**Comment by tjayrush** [comment]
The 'fullBlocks' methodology is long gone, so this particular issue is no longer the case. Closing.
