### ISSUE TITLE
Remove this hacky code

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/trueblocks-core#1014]
::remove("/root/.quickBlocks/cache/fullBlocks.bin.lck");

**Comment by tjayrush** [comment]
Related to #1012

**Comment by wildmolasses** [comment]
We inserted this code because of the docker image quit problem. We could bring it down a level of hackiness by removing this file in the docker entrypoint instead of in the C++ code.

**Comment by tjayrush** [comment]
So this only exists if we're running the docker? I like that. If you like, please go ahead and do that.

**Comment by tjayrush** [comment]
The fullBlocks methodology is long gone. Closing.
