### ISSUE TITLE
Add unique ID per monitor group

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/trueblocks-core#1020]
User feature request:

If the user is using the 'push' feature, he/she should be able to specify a unique id or tag per monitor group. This would be useful to identify the incoming data in the client code.

**Comment by Mechrophile** [comment]
For my purposes, exposing any stable unique value in the payload from the monitor is sufficient, it just needs to be guaranteed no to change and guaranteed not to be the same in different monitors.

**Comment by tjayrush** [comment]
This is an application level issue. Closing.
