### ISSUE TITLE
chifra monitoring "address-only" approach

### ISSUE THREAD

**Issue by wildmolasses** [Great-Hill-Corporation/trueblocks-core#1028]
We talked a bit about not requiring a name for chifra monitoring files. To recap some of the stuff we discussed. We could bring the naming somewhere else. We also talked about not grouping watches into monitors prematurely. This would leave a monitor folder filled with address folders. `chifra ls` would give addresses then.

The monitor config items in `config.toml` could go elsewhere. Export formats for example. We could use these as "recipes" for `chifra export`. `chifra export [recipe]` or `chifra export --address 0x1...b,0x1...c,0x9...f --format {{specifiedhere}}`

The recipes can include groupings, format, and useful other stuff that config.toml already provides.

**Comment by tjayrush** [comment]
We need to talk about this. Machines (and API) probably want addresses, but user definitely do not. So users (who presumably would be using `chifra ls` want names (I think).

Although, I completely agree with the 'address-first' approach. It nice to have that issue separated out and clarified.

**Comment by tjayrush** [comment]
This has been resolved (Thanks Ed). We now store each monitor list in a separate file per address. If we need more than one address at a time, we merge the data so as to eliminate dups, etc. Works excellently, and has for some time.
