### ISSUE TITLE
chifra MVP features

### ISSUE THREAD

**Issue by wildmolasses** [Great-Hill-Corporation/trueblocks-core#1029]
Here are some ideas on how I see chifra working. I'll keep it simple MVP style. It's inspired by your existing implementation with some small differences. Supports cached and uncached addresses, uses single-address approach

### `chifra scrape`
- generates the account index

### `chifra list [address]`
- returns the grepped account index for [address]
- looks first to see if there's a cache. if yes, read from cache. if not, grep addr index.

### `chifra init [address]` or `chifra cache [address]`
- greps addr index and stores result in cache

### `chifra daemon`
- freshens cached addresses

### `chifra export --format [format string] [address]`
- hits the rpc, returns articulated data for each tx from `address`'s tx index.
- should use `chifra list [address]` to get tx index (aka looks first to see if there's a cached list, and if not, grep the addr index).

**Comment by tjayrush** [comment]
Let's work on this type of stuff for chifra. Sort of like a top-down design. We can do this in 'go' since it has such a better command line help processing features. Once we have a top-level design, we can move one tool over at a time (bringing over only what makes sense), and then depreciate the C++ code.

**Comment by tjayrush** [comment]
I feel like the API needed for the MVP is pretty well understood, so this can be closed. There will be further work on the API, but we are at least as far as MVP.
