### ISSUE TITLE
"chifra progress"

### ISSUE THREAD

**Issue by wildmolasses** [Great-Hill-Corporation/trueblocks-core#1099]
I’m going to suggest and implement a “chifra progress” command where the user can see…
- ~Where is the scrape at, relative to the head of chain? (And where is the chain at?)~
- ~Where is the indexing consolidation at? Aka how much index has been finalized (green), how much is data waiting to be indexed (yellow), how much data is head-of-chain unfinalized (red)? Let me see all of this.~
- ~Might also list some other useful information, such as cache path, rpc provider, etc. But this should be more global.~
- ~In addition to printing to console, we need to consume this information in trueblocks-explorer.~

**Comment by wildmolasses** [comment]
Perhaps `chifra status`, extending vocabulary from elsewhere...

**Comment by tjayrush** [comment]
@wildmolasses This is sort of available by sending `getBlock --latest`, but it's poorly formatted, running from the wrong tool (shouldn't be `getBlock`), and incomplete. Can you post below the sort of data you might like to see? Here's results from running the command currently:

```
(develop)@./build:jrush>$ getBlock --latest
  Client version:     Parity-Ethereum//v2.3.4-beta-0e95db11d-20190220/x86_64-macos/rustc1.32.0
  Trueblocks version: GHC-TrueBlocks//0.5.8-alpha-d0f43c27-20190728
  RPC provider:       http://localhost:8545
  Cache location:     /Volumes/Samsung_T7/testing/
  Host (user):        Thomass-iMac.lan (jrush)
  Heights:              8252320,   8253783,   8253783,   8253811,   8253812
  Previous Heights:     8252320,   8253783,   8253783,   8253811,   8253811
  Distances:               1492,        29,        29,         1,         0
  Diffs:                      0,         0,         0,         0,         1
  Neighbors:                  0,     -1463,         0,       -28,         0
--------------------------------------------------------------------------------------- 15:13:45

```

**Comment by tjayrush** [comment]
Incorporating #1131 as a duplicate.

**Comment by tjayrush** [comment]
Most of this information in now available in the /status route of the API (and by extension the `status` option to `chifra`). Closing. If we need additional information, we can handle it through additional issue to the docker repo.
