### ISSUE TITLE
finalized index stored in different folder; expose this as config option

### ISSUE THREAD

**Issue by wildmolasses** [Great-Hill-Corporation/trueblocks-core#1106]
We discussed how the finalized index is stored in a separate file location. Ideally it belongs on an SSD. If this is different than the user's blockCachePath, so be it. But the user should have some insight into our filesystem opinions. The indexPath could be set in quickBlocks.toml. ~~Furthermore, folder locations should appear in the logs. `chifra ls`, aside from showing the monitor folder location, could show other key locations. `chifra status` could output these folder locations as well.~~

**Comment by tjayrush** [comment]
I separated out the issue related to `chifra ls` in this issue: #1131

**Comment by tjayrush** [comment]
I am going to close this. There is a config item called `indexPath`. All of the config options will be documented, so we don't have to track this one separately.
