### ISSUE TITLE
Aside from logging, other dedicated streams are needed

### ISSUE THREAD

**Issue by wildmolasses** [Great-Hill-Corporation/trueblocks-core#1111]
For example, acctExport needs to communicate its progress to the trueblocks-explorer.

**Comment by tjayrush** [comment]
I'm not sure this is true. I think we can have a single `data` channel (i.e. standard out) and a `message` channel (i.e. standard error). If we find the need for other channels, my hope is that they are focused and specific per tool.

We can use the message channel in multiple ways. So, for example, the application/tools code could simply write to standard err, and behind the scenes that can be sent along to the calling context and at the same time be logged (if it is of a certain severity).

Unless you have specifics, please close this.

**Comment by wildmolasses** [comment]
One such specific stream is "export progress." When `chifra export [address]` is run, a full result set could take 5 minutes or longer (let's put aside pagination for the moment). We can think of `chifra export` representing its progress with the following data structure:

```
{
    "totalRecords": 104153,
    "currentRecord": 1302
}
```

`chifra export` will be updating this data quite frequently, and the consumer of this data will want to know it often as well.

I think that the stdout/stderr will not be sufficient for this problem. So then we think of writing it to a separate stream / file.

As you said, though, this could be tool specific, and not a general stream that we need to manage throughout the application.

**Comment by tjayrush** [comment]
> I think that the stdout/stderr will not be sufficient for this problem.

Why? Can't we just separate channels by prefixing the messages?  INFO: ERROR: PROGRESS:

The one slight concern I have is cleanup of streams when users quit early.

**Comment by tjayrush** [comment]
I'm going to close this. I'm not sure it's true that we need more 'channels.' The MVP works with stdout for data, stderr for 'reporting/progress/status'. We can prepend 'MSG:' types to any messages on the stderr channel without complicating things with a new channel.
