### ISSUE TITLE
Quickstart links to samples, broken link

### ISSUE THREAD

**Issue by TimDaub** [Great-Hill-Corporation/trueblocks-core#1147]
This page: https://quickblocks.io/docs/quickstart.html links here: https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/src/samples

That link is broken.

This might be the correct links:
- https://github.com/Great-Hill-Corporation/trueblocks-core/tree/master/docs
- https://github.com/Great-Hill-Corporation/trueblocks-core/tree/develop/src/examples

**Comment by tjayrush** [comment]
Fixed. Thanks for letting us know. If you find anything else, please make another issue.
