### ISSUE TITLE
Typo in scraper consolidation

### ISSUE THREAD

**Issue by wildmolasses** [Great-Hill-Corporation/trueblocks-core#1187]
![Screen Shot 2019-07-30 at 6 38 48 PM](https://user-images.githubusercontent.com/5423313/62170418-52f68800-b2f9-11e9-9181-335368c950f3.png)

Noticed consolodate in one place and consolidate in another. Consolidate is correct!

**Comment by tjayrush** [comment]
Fixed with latest commit. You may close this.
