### ISSUE TITLE
Long running queries that cannot get stopped (on dAppNode for example) will cause problems

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/trueblocks-core#1194]

**Comment by wildmolasses** [comment]
Why don't the queries stop?

From an API point of view, the queries stop when the curl or fetch request is aborted. This sends SIGINT to the chifra process. In that case, chifra should properly respond to SIGINT and stop.

**Comment by tjayrush** [comment]
I am going to close this as a duplicate of #69. Let's take this discussion over there.
