### ISSUE TITLE
Implement setConfig route in chifra

### ISSUE THREAD

**Issue by wildmolasses** [Great-Hill-Corporation/trueblocks-core#1214]
The api wants to set config parameters like rpc_provider and api_key. chifra should give the api an interface to do so.

**Comment by tjayrush** [comment]
How would you like to handle this? I would prefer to be sent the entire JSON data structure that the backend sends out to the front end as an escaped string. So:

-- front end asks for config data
-- backend sends the entire JSON data structure
-- front end allows the user to edit and sends exactly same data structure with edited values.

You could, if you wished, strip out UI related data such as `tip`, `type`, `required`. I don't really need. I only need the structure and the new values. The backend will validate the data and silently ignore any invalid data (i.e. won't store the change). The frontend should verify the data as well, and generally speaking send only good data, so as to avoid a round trip.

**Comment by wildmolasses** [comment]
Hi Jay, just recording here that we discussed your question above in calls. Let me know if you want an articulation of what we discussed here in the comments.

**Comment by tjayrush** [comment]
No need. I just wanted to point out that this issue is blocked.
