### ISSUE TITLE
chifra should provide current config values of interest

### ISSUE THREAD

**Issue by wildmolasses** [Great-Hill-Corporation/trueblocks-core#1215]
The front end needs to know what current config values are, such as rpc_provider (already in status route) and api_key.

an example implementation would be

`chifra config`

and would return:

```
{
  "data": {
    "quickBlocks": {
      "rpcProvider": "http://localhost:8545"
    },
    "ethslurp": {
      "api_key": "40315-3013051-053105103"
    }
  }
}
```

**Comment by tjayrush** [comment]
Added a spreadsheet documenting all config items: https://github.com/Great-Hill-Corporation/trueblocks-core/blob/develop/src/other/docs/Toml_config_data.xlsx.

Here's a PDF version: [https://app.zenhub.com/files/87072460/0f80e487-cd91-44df-9e1b-61c281d0d023/download](https://app.zenhub.com/files/87072460/0f80e487-cd91-44df-9e1b-61c281d0d023/download)

**Comment by tjayrush** [comment]
May I suggest an alternative?

If I do this command from the command line:

```
cat ~/.quickBlocks/quickBlocks.toml  | tr '\n' '`' | sed 's/\"/\\"/g'
```

I get this string

```
[version]`current=\"0.5.5-alpha\"``[settings]`#rpcProvider = \"http://my.ethchain.dnp.dappnode.eth:8545/\"`#rpcProvider=\"http://127.0.0.1:7545\"`#rpcProvider=\"mainnet.infura.io/v3/f62d307787fe4f4ea18be11aa2b60811\"`balanceProvider=\"http://wildmolasses:8080/\"`cachePath=\"/Volumes/Samsung_T7/scraper/\"`indexPath=\"/Users/jrush/.quickBlocks/cache/addr_index/\"`
```

When you receive this string, you can simply replace `\"` with `"` and `\'` with a newline. You will then have a valid TOML formatted string which you can handle via some TOML library. You can convert to JSON and then re-convert back to TOML with the new values.

When you send it, simple change newlines to '`' and escape quotes.

In this way, I won't have to write TOML 'writing' code, nor will I have to build a whole 'infrastructure'  (which means a collection of C++ classes) to handle this data.

Delivering the data to you in this format would be a one liner (litterally) in my code:

```
cout << substitute(substitute(asciiFileToString(filename.toml), "\"", "\\""), "\n", "`");
```
and writing it back out to disc would be a one liner as well.

```
stringToAsciiFile(substitute(substitute(editedStr, "\\"", "\""), "`", "\n");
```

Let's discuss.

**Comment by wildmolasses** [comment]
Hey Jay, exploring the alternative you proposed. Some questions for you:

In this alternative that you propose...

- is there a `chifra config`?
- If yes, does it show config values? It seems like it's a wrapper around `cat ~/.quickBlocks/quickBlocks.toml  | tr '\n' '`' | sed 's/\"/\\"/g'`. And then it formats it better. So yes, it shows config values. You're exploring the idea of the js api doing the toml -> json conversion. But this deviates from our ideal of the api being a thin wrapper around the core.
- How will other config files be accessed (such as ethslurp.toml)? Would that be `chifra config --file=ethslurp.toml`?
- Does chifra handle the updating at all? I.e. is there a `chifra config set --api_key 130350-0315-01-5031`? It seems like the answer is no. Is there a `chifra config --file=ethslurp.toml --replace="NEW_CONFIG_FILE_AS_STRING"`? If the answer there is no, then the js api is updating the toml files directly. But this again seems to deviate from our ideal of the api being a thin wrapper around the all-intelligent core.
- should the js api "know" about which toml files are stored where? How does it know?
- should the js api know which settings are contained in which toml files?


To look again at providing a config interface directly from chifra, here's a brainstorm of some benefits:
- all applications could get and set config values, whether they're using the api or not.
- trueblocks-core retains control over config structure and logic. trueblocks-core could implement an entirely different config strategy without any adjustment to dependent apps / api
- demystifies config for the user -- instead of going in through filesystem, can adjust config straight from the tool and even be chaperoned by tool.

**Comment by tjayrush** [comment]
So I'm going to send you JSON data as you originally proposed. It's going to look like this:

```
![image.png](https://images.zenhubusercontent.com/5d681f7336b12077dd1bb365/6d98031c-4acb-4493-9995-4a670e35e780)
```

**Comment by tjayrush** [comment]
Notes on the data:

1. The format probably won't change much from now on.
2. Numeric (uint) and boolean values are sent as strings, but you can tell their type from the `type` field.
3. The custom names array will be sent as a string as well. Quotes are escaped.

The fact that all values are sent as strings is expediency related to inadequacies of our C++ json code. This will never be fixed. Instead, we will suffer through it until the code can be ported to Go (or preferably Rust).

**Comment by tjayrush** [comment]
Not sure how to handle this issue from here, but I think it can be closed. If we close it, we should open another issue to enable editing these values in the front end.

**Comment by wildmolasses** [comment]
`JSON.stringify(`json here`)

```
"{ \"type\": \"CConfiguration\", \"data\": [\n{\n  \"files\": [\n    {\n      \"name\": \"quickBlocks.toml\",\n      \"groups\": [\n        {\n          \"name\": \"settings\",\n          \"keys\": [\n            {\n              \"name\": \"rpcProvider\",\n              \"value\": \"--rpcProvider--\",\n              \"type\": \"url\",\n              \"tip\": \"the Ethereum node's RPC endpoint\",\n              \"required\": true,\n              \"read_only\": false\n            },\n            {\n              \"name\": \"apiProvider\",\n              \"value\": \"--apiProvider--\",\n              \"type\": \"url\",\n              \"tip\": \"TrueBlocks' API endpoint\",\n              \"required\": true,\n              \"read_only\": false\n            },\n            {\n              \"name\": \"balanceProvider\",\n              \"value\": \"--balanceProv--\",\n              \"type\": \"url\",\n              \"tip\": \"alternative node endpoint for account balances\",\n              \"required\": false,\n              \"read_only\": false\n            },\n            {\n              \"name\": \"configPath\",\n              \"value\": \"--configPath--\",\n              \"type\": \"path\",\n              \"tip\": \"location of config files, read only\",\n              \"required\": true,\n              \"read_only\": true\n            },\n            {\n              \"name\": \"cachePath\",\n              \"value\": \"--cachePath--\",\n              \"type\": \"path\",\n              \"tip\": \"location of cache (on external SSD, for example)\",\n              \"required\": false,\n              \"read_only\": false\n            },\n            {\n              \"name\": \"indexPath\",\n              \"value\": \"--indexPath--\",\n              \"type\": \"path\",\n              \"tip\": \"location of index (on internal SSD for speed)\",\n              \"required\": false,\n              \"read_only\": false\n            }\n          ]\n        }\n      ]\n    },\n    {\n      \"name\": \"blockScrape.toml\",\n      \"groups\": [\n        {\n          \"name\": \"settings\",\n          \"keys\": [\n            {\n              \"name\": \"nBlocks\",\n              \"value\": \"--nBlocks--\",\n              \"type\": \"uint\",\n              \"tip\": \"number of blocks to process per invocation of blaze (> 50)\",\n              \"required\": true,\n              \"read_only\": false\n            },\n            {\n              \"name\": \"nAddrProcs\",\n              \"value\": \"--nAddrProcs--\",\n              \"type\": \"uint\",\n              \"tip\": \"number of parallel go processes to use to process addresses (> 0)\",\n              \"required\": true,\n              \"read_only\": false\n            },\n            {\n              \"name\": \"nBlockProcs\",\n              \"value\": \"--nBlockProcs--\",\n              \"type\": \"uint\",\n              \"tip\": \"number of parallel go processes to use to process blocks (> 0)\",\n              \"required\": true,\n              \"read_only\": false\n            }\n          ]\n        }\n      ]\n    },\n    {\n      \"name\": \"acctExport.toml\",\n      \"groups\": [\n        {\n          \"name\": \"settings\",\n          \"keys\": [\n            {\n              \"name\": \"writeTxs\",\n              \"value\": \"--writeTxs--\",\n              \"type\": \"bool\",\n              \"tip\": \"write transactions to the TrueBlocks binary cache\",\n              \"required\": false,\n              \"read_only\": false\n            },\n            {\n              \"name\": \"writeTraces\",\n              \"value\": \"--writeTraces--\",\n              \"type\": \"bool\",\n              \"tip\": \"write traces to the TrueBlocks binary cache\",\n              \"required\": false,\n              \"read_only\": false\n            }\n          ]\n        },\n        {\n          \"name\": \"balances\",\n          \"keys\": [\n            {\n              \"name\": \"remote\",\n              \"value\": \"--remote--\",\n              \"type\": \"bool\",\n              \"tip\": \"get balances from balanceProvider\",\n              \"required\": false,\n              \"read_only\": false\n            }\n          ]\n        }\n      ]\n    },\n    {\n      \"name\": \"ethslurp.toml\",\n      \"groups\": [\n        {\n          \"name\": \"settings\",\n          \"keys\": [\n            {\n              \"name\": \"api_key\",\n              \"value\": \"--api_key--\",\n              \"type\": \"string\",\n              \"tip\": \"api key required to use EtherScan apis -- private data -- not shared\",\n              \"required\": false,\n              \"read_only\": false\n            }\n          ]\n        }\n      ]\n    },\n    {\n      \"name\": \"getAccounts.toml\",\n      \"groups\": [\n        {\n          \"name\": \"custom\",\n          \"keys\": [\n            {\n              \"name\": \"list\",\n              \"value\": \"[{ \"address\": \"0x3b1613b1613b1613b1613b1613b1613b1613b161\", \"name\": \"TestWallet1\" },{ \"address\": \"0xb1661b1661b1661b1661b1661b1661b1661b1661\", \"name\": \"TestWallet2\" }]\",\n              \"type\": \"json array\",\n              \"tip\": \"user specific list of names for addresses -- private data -- not shared\",\n              \"required\": false,\n              \"read_only\": false\n            }\n          ]\n        }\n      ]\n    }\n  ]\n}\n\n], \"meta\": {\"unripe\": \"0xdeadbeef\",\"ripe\": \"0xdeadbeef\",\"staging\": \"0xdeadbeef\",\"finalized\": \"0xdeadbeef\",\"client\": \"0xdeadbeef\" } }"
```

**Comment by wildmolasses** [comment]
Hi Jay, can you write a comment here about what you'd like me to review?

**Comment by tjayrush** [comment]
This data is ready for your review. If you think it meets your needs, please close this issue.

**Comment by wildmolasses** [comment]
After checking out the data on a `chifra config get`, it looks spectacular and is valid JSON. So I'm going to move this to "done." Let's keep the issue open until the end of the sprint.

**Comment by tjayrush** [comment]
Moving to the Done pipeline.
