### ISSUE TITLE
Chifra should respond to API's SIGINT

### ISSUE THREAD

**Issue by wildmolasses** [Great-Hill-Corporation/trueblocks-core#1225]
Steps to create the problem:

- with the API running locally, do a long running query like an export on the cryptokitties address (`curl http://localhost:8080/export?....`)
- after the request has started to process, cancel the request (ctrl-c on curl)
- at this point, the api has sent a SIGINT to chifra.
- check `ps -ef | grep ...` to see that the long running chifra query is still running.

Potential helpers on this issue: log signal being received in api, in chifra, and in chifra child tools

**Comment by tjayrush** [comment]
Copied from closed issue:

Start the API in one window.

In another shell enter this command:

```
curl http://localhost:8080/export?address=`ethName -a tip`
```

You should see JSON data in the current window and status reporting in the first window. Hit control+C before the export finishes. Do this ten - fifteen times (starting the curl command and hitting Control+C before it finishes).

You get this report in the first window after a while:

```
TrueBlocks API initialized on port 8080
(node:31373) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unpipe listeners added. Use emitter.setMaxListeners() to increase limit
(node:31373) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added. Use emitter.setMaxListeners() to increase limit
(node:31373) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:31373) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit
(node:31373) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 finish listeners added. Use emitter.setMaxListeners() to increase limit
```

**Comment by tjayrush** [comment]
I think this is now working as it should.
