### ISSUE TITLE
On port change, trueblocks thinks it's at block 0.

### ISSUE THREAD

**Issue by wildmolasses** [Great-Hill-Corporation/trueblocks-core#1234]
From manage#78,

If the rpcProvider is changed to a different port, say 8145, then important commands against the rpc will not work as intended. I haven't tested thoroughly, but for starters, `getBlock 3030300` responds that 3030300 is later than the last block, 0.

**Comment by tjayrush** [comment]
One thing you can try is to put a variable inside of `~/.local/share/trueblocks/trueBlocks.toml` (or `~/Library/Application Support/TrueBlocks/trueBlocks.toml` on a Mac) thus:

```
[dev]
debug_curl = true
```

Rerun the command you're having trouble with.

This will print out the (many, many) interactions with the node. My guess is that the we're getting an error response that TrueBlocks blindly (and stupidly) fails to respond to.

Another thing to try to `getBlock 3003003 --raw` which is supposed to report the exact JSON returned from the node. If that doesn't work, try `getBlock 3003003 --veryRaw` (although this last one may not work -- if it doesn't let me know.

**Comment by wildmolasses** [comment]
As Jay said in manage#78..

Results from `getBlock 3003003` against port 8145:

```
------------------------------------------------------------------------------------------------------------------------
.postData: {"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":"1"}
	result: 	[]
	earlyAbort: 	0
	curlID: 	2
------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------
.perform:
	method:		eth_getBlockByNumber["latest",false]
	source:		binary
	result: 	[]
	earlyAbort: 	0
	curlID: 	3
------------------------------------------------------------------------------------------------------------------------
.postData: {"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["latest",false],"id":"4"}
	result: 	[]
	earlyAbort: 	0
	curlID: 	5
------------------------------------------------------------------------------------------------------------------------
.data->result ==> Provided Host header is not whitelisted.

------------------------------------------------------------------------------------------------------------------------
.CURL returned CURLE_OK
	result: 	[Provided Host header is not whitelisted. ]
	earlyAbort: 	0
	curlID: 	6
------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------
.Received: Provided Host header is not whitelisted.

	result: 	[Provided Host header is not whitelisted. ]
	earlyAbort: 	0
	curlID: 	7

  Block 3003003 is later than the last valid block 0.
```

**Comment by wildmolasses** [comment]
I asked Joshua from Parity about this. waiting to hear back.

![Screen Shot 2019-09-03 at 3 16 37 PM](https://user-images.githubusercontent.com/5423313/64201936-ea517c80-ce5d-11e9-9cce-e5dd0e2805bf.png)

**Comment by tjayrush** [comment]
I think this can be closed.
