### ISSUE TITLE
Config Page Epic

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/trueblocks-core#1251]

**Comment by wildmolasses** [comment]
should include some insight into what to do when there are errors and at which phase.

Did the `chifra get` api request fail? What happens and when?
Did the `chifra set` api request fail? What happens and when?

All good, just recording this before I forget it.

**Comment by wildmolasses** [comment]
Also, testing

**Comment by wildmolasses** [comment]
What happens when a config option changes names in the `chifra config get` route?

**Comment by tjayrush** [comment]
> What happens when a config option changes names in the chifra config get route?

I would make the frontend form generic enough so that whatever data the backend sends from `chifra config get` could be presented and edited without coordination. I probably wouldn't refer to the field names directly. This is why I included a `name`, `value`, `tooltip`, `type`, `required` and `read_only` in the JSON. Those data make it possible to write a generic form that accepts and allows editing of any data. If the frontend's form were 'generic' in this sense, then the backend could send whatever data it wanted to without even consulting the front end.

I would do this for all of the forms in the frontend. I would probably also make them React components. One for each field's label, one for each field's edit control, one for each field's validation (maybe?), one for the form itself (a container of fields), etc. 

Without having investigated it, my guess is this is why using a React Component library is a good idea.
