### ISSUE TITLE
Old Notes on the Database (reference only)

### ISSUE THREAD

**Issue by wildmolasses** [Great-Hill-Corporation/trueblocks-core#1258]
Make a draft of the schema diagram that we can talk about.

A subsequent discussion might include:
- do we need this piece of data? will we in the future?
  - redundant data: timestamp on transaction = timestamp on block?
- what columns could we add? (transaction type: internal, external, etc; would enhanced bloom filters be useful in db?)
- column types (function names could be ENUM, value field DECIMAL, NUMERIC, BIGINT)
- what about the data could change?
  - columns, column types, block mistakes
- what is the fastest way to index & query?
- size/scaling constraints?

**Comment by tjayrush** [comment]
![image.png](https://images.zenhubusercontent.com/5d681f7336b12077dd1bb365/a304e26e-aab0-4533-b650-2746a3c3eac2)

**Comment by tjayrush** [comment]
This is a very interesting discussion. I think it can be closed. I have these documents (i.e. the images) stored elsewhere if we ever need them for documentation.
