### ISSUE TITLE
Config Page Mock Up

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/trueblocks-core#1264]
![image](https://user-images.githubusercontent.com/5417918/64724351-56586400-d4a0-11e9-93ea-ae47c45ab582.png)

The format of the data is here: https://app.zenhub.com/workspaces/trueblocks-workspace-5d680eb2a00eda0001a1bd65/issues/great-hill-corporation/trueblocks-core/1215

**Note:** the first option under `Export` (`remoteBals`) has been removed. No need for it.

**Comment by wildmolasses** [comment]
The config page has indeed been mocked out and lives as a component. Additional functionality should belong as separate issues.
