### ISSUE TITLE
Decide how `chifra config set` looks in core and in api

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/trueblocks-core#1265]
Use <INSERT_DATA_HERE>

How should the CLI look, and how should the API look?

Implement this in both the CLI (core) and in the api.

**Comment by wildmolasses** [comment]
Hey Jay, I might need help on this. Specifically, what does `chifra config set` look like as an api route?

**Comment by wildmolasses** [comment]
After looking at the csv, it looks like I can update the config with...

`/status?config-set=<config_string>`

Does that seem correct?

**Comment by tjayrush** [comment]
I'm not really sure to be honest. How does one usually send a string of JSON (or any other type of data) to an API call? In the old days, we would use a PUT because GET had a limit of 1024 characters or something. PUT allowed an arbitrary amount of space.

On teh command line I would just put it in double quotes and escape any double quotes in the string.

**Comment by wildmolasses** [comment]
> I'm not really sure to be honest. How does one usually send a string of JSON (or any other type of data) to an API call? In the old days, we would use a PUT because GET had a limit of 1024 characters or something. PUT allowed an arbitrary amount of space.

Let's try it as a GET right now. Let's try passing it in as a parameter. But can you enable it somehow as an api route?

> On teh command line I would just put it in double quotes and escape any double quotes in the string.

In my code I will do the double quoting and escaping before I pass the new settings payload to the api route.

**Comment by tjayrush** [comment]
I think there already is a route. It’s `chifra config put <str>` (but there’s an issue to change that to `set`.)

Should I change it now or wait until later?

Also — I’m not sure it will work — because I really didn’t know what the string would look like, so I mocked something up. (In other words, I ignore the string from the command line and use a default string.)

Go ahead and enable the ’submit button’ or whatever it is, I will pul the front end, and play with it. I may have to fix something in my code.

Does that make sense?

-------------------------------
Thomas Jay Rush
TrueBlocks.io
jrush@trueblocks.io
(610) 937-2593

**Comment by tjayrush** [comment]
This is now working. I am going to move it to 'Done.'

There are a few issues that I will add regarding how it behaves, however. I'll copy links back in here.
