### ISSUE TITLE
config set does not appear to work

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/trueblocks-core#1272]
When I press the submit button on the config page, I get this result:

![image](https://user-images.githubusercontent.com/5417918/65007873-6d021f00-d8d5-11e9-9b24-772e3fb5e62d.png)

One note that may help -- you only need to send the `key` and the `value` not the rest of the data. I only send the rest of the data FYI.

**Comment by wildmolasses** [comment]
Thanks. I'll close this because we're working on the spec.
