### ISSUE TITLE
Update chifra config get: group and subset for control panel

### ISSUE THREAD

**Issue by wildmolasses** [Great-Hill-Corporation/trueblocks-core#1275]
`chifra config get` should expose some way to limit the results returned to **only** those required for the front end control panel.

Furthermore those results should be grouped.

The data structure could look like this:

```
[
  "Providers": [
     {"name": "rpcProvider", "value": "http://localhost:36963", "tip": "rpc val!", etc etc},
     {"name": "other thing" ....}
]
]
```

**Comment by tjayrush** [comment]
This is done.
