### ISSUE TITLE
Issues with JSON:API documentation requirements and streaming data

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/trueblocks-core#1285]
Ed:

```
OK, can you post to the issue about what's changed

Of all the possible responses, which return complete json? is there still a
risk anywhere of incomplete json? is it impossible to know because of
lack of testing? and then, lets assume that this issue is separate from
adhering to canonical json response shape, and let's note that

Just some questions in my head
```

Jay:

```
The code tries to not quit early unless it's in a crazy state. On the command
line, it legit to simply report an error to cerr and stop processing. In the API 
mode, that's not desired. (Sorry to take this moment to remind us both that 
we're not build an API-based, browser-based application).

Without proper testing, it's hard to find these places where it quits out early -- 
although they are not numerous -- mostly when the RPC disappears or 
something crazy happens like can't read the hard drive.

As I look more into the JSON:API document I pointed to earlier, I'm finding 
a fundamental disconnect between it and a desire to produce a 'stream' of data.

That document says the response should have either an element error or an
item data but it MUST not have both.

If this is the case, I'm not sure how to begin a stream of data, find an error during
processing, and then backup and take data away from the stream.

My expectation is that I will ignore that MUST, because it's important to me to
stream the data (i.e. not collect it in memory before starting to deliver it).
```

**Comment by wildmolasses** [comment]
I'm going to throw an idea or 2 out there.

1st of all, chifra could stream to a file, and then upon successful completion stream the file to the api.

Not sure if that meets our needs.

Another thing. With pagination, streaming results seems a lot less of an imperative. A page of results can be easily held in memory.

I think we should try if we can to follow the JSON:API spec regarding the mutually exclusive errors and data array inclusion.

**Comment by tjayrush** [comment]
> Another thing. With pagination, streaming results seems a lot less of an imperative. A page of results can be easily held in memory.

This is exactly the point. The API spec is imposing on the implementation. On the command line (and in a desktop app), when an error is encountered, you can simply quit processing, report the error, and be done. You don't have to 'hold back' on the delivery of the `data` until you decide if you've completed without an error. It's literally 100s of times faster to not "hold-back" the data.

I could implement two paths, one for the API and one for non-API, but that bring complications. If instead, we loosen the rule for `errors/data` being in the same response and instead simply allow `errors` to predominate (if `errors` is present, the response is an error) I can avoid the 'holding back'.
