### ISSUE TITLE
utillib: toml files should have an upgrade process

### ISSUE THREAD

**Issue by wildmolasses** [Great-Hill-Corporation/trueblocks-core#1393]
When significant changes to a toml file change in the repo, we should have an upgrade process.

One idea is to start with a base toml that always gets overwritten. User customizations could live in another file that supersedes the base config.

**Comment by tjayrush** [comment]
I've tried multiple times to fix the 'toml' issue. It's not going to happen. We can 'fix it' when we port to 'go'.

**Comment by tjayrush** [comment]
Not fixing toml.
