### ISSUE TITLE
Error running make in string.h

### ISSUE THREAD

**Issue by MysticRyuujin** [Great-Hill-Corporation/trueblocks-core#1478]
I was trying to make the project just now and I received the following error:

I'm on Ubuntu 20.04 LTS

```
In file included from /usr/include/string.h:495,
                 from /mnt/e/trueblocks/trueblocks-core/src/libs/utillib/basetypes.h:32,
                 from /mnt/e/trueblocks/trueblocks-core/src/libs/utillib/utillib.h:14,
                 from /mnt/e/trueblocks/trueblocks-core/src/libs/etherlib/known_blocks.h:14,
                 from /mnt/e/trueblocks/trueblocks-core/src/libs/etherlib/etherlib.h:14,
                 from /mnt/e/trueblocks/trueblocks-core/src/libs/acctlib/accountwatch.h:18,
                 from /mnt/e/trueblocks/trueblocks-core/src/libs/acctlib/acctlib.h:14,
                 from /mnt/e/trueblocks/trueblocks-core/src/apps/cacheStatus/options.h:11,
                 from /mnt/e/trueblocks/trueblocks-core/src/apps/cacheStatus/options.cpp:10:
In function ‘char* strncpy(char*, const char*, size_t)’,
    inlined from ‘virtual void COptions::Init()’ at /mnt/e/trueblocks/trueblocks-core/src/apps/cacheStatus/options.cpp:201:16:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:34: error: ‘char* __builtin_strncpy(char*, const char*, long unsigned int)’ output truncated before terminating nul copying 6 bytes from a string of the same length [-Werror=stringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [apps/cacheStatus/CMakeFiles/cacheStatus.dir/build.make:310: apps/cacheStatus/CMakeFiles/cacheStatus.dir/options.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:4576: apps/cacheStatus/CMakeFiles/cacheStatus.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

```
cmake version 3.16.3
```

**Comment by tjayrush** [comment]
Thanks for reporting.

Weird bug on Ubuntu 20.04 only. I updated the one line giving trouble, and it should build now.

I also caught the master branch up to the develop branch so you’ll get all the latest code in master.

Do:

	git pull
	cmake ../src
	make

And it should build.

If you need any help at all, let me know.

-------------------------------
Thomas Jay Rush
TrueBlocks.io
jrush@trueblocks.io
(610) 937-2593

**Comment by MysticRyuujin** [comment]
New error :)

```
[ 21%] Building CXX object libs/acctlib/CMakeFiles/acct.dir/monitor.cpp.o
/mnt/e/trueblocks/trueblocks-core/src/libs/acctlib/monitor.cpp: In member function ‘bool qblocks::CMonitor::loadAndSort(qblocks::CAppearanceArray&)’:
/mnt/e/trueblocks/trueblocks-core/src/libs/acctlib/monitor.cpp:598:58: error: ‘void bzero(void*, size_t)’ clearing an object of non-trivial type ‘struct qblocks::CAppearance_base’; use assignment or value-initialization instead [-Werror=class-memaccess]
  598 |         bzero(buffer, nRecords * sizeof(CAppearance_base));
      |                                                          ^
In file included from /mnt/e/trueblocks/trueblocks-core/src/libs/etherlib/etherlib.h:27,
                 from /mnt/e/trueblocks/trueblocks-core/src/libs/acctlib/monitor.h:18,
                 from /mnt/e/trueblocks/trueblocks-core/src/libs/acctlib/monitor.cpp:18:
/mnt/e/trueblocks/trueblocks-core/src/libs/etherlib/appearance.h:215:8: note: ‘struct qblocks::CAppearance_base’ declared here
  215 | struct CAppearance_base {
      |        ^~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [libs/acctlib/CMakeFiles/acct.dir/build.make:154: libs/acctlib/CMakeFiles/acct.dir/monitor.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1971: libs/acctlib/CMakeFiles/acct.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

**Comment by tjayrush** [comment]
I’m seeing the same thing. I’m posting updates to ‘develop’ branch shortly.

Sorry for the trouble. Hang in there. It actually works again your node.

Once you get it compiled do this to see if it works:

From the ./build folder

	cd ../bin
	./getBlock 100

This may return data (in which case it’s working) or it may return an error saying can’t find localhost:8545.

If the later, edit a file called ~/.quickBlocks/quickBlocks.toml and change the rpcProvider to your node RPC and try again.

Should return block data.

Then try something like this:

	./getBlock 1001001 —uniq_tx

from the bin folder.

I’ll email you as soon as the fix is in place.


=======================
Thomas Jay Rush
TrueBlocks, LLC
jrush@trueblocks.io
Twitter: @quickblocks

**Comment by tjayrush** [comment]
Hey Chase.

Thanks for hanging in there with me. I had never built on Ubuntu 20.04 before, so there were a few issues. They should all be fixed now.

Can you try it again?

=======================
Thomas Jay Rush
TrueBlocks, LLC
jrush@trueblocks.io
Twitter: @quickblocks

**Comment by MysticRyuujin** [comment]
I was able to build. It seems to be working... Opened a new issue over on trueblock-explorer though

**Comment by tjayrush** [comment]
Did you add the ./trueblocks-core/bin to your PATH?

You will know if you did if you can type getBlock or chifra from anywhere on your terminal.

Type ‘chifra —help verbose’ for a list of all commands.

(chifra is an overriding tool that covers all the other tools so you don’t have to use getBlock for example— you can use `chifra blocks` instead).

=======================
Thomas Jay Rush
TrueBlocks, LLC
jrush@trueblocks.io
Twitter: @quickblocks

**Comment by MysticRyuujin** [comment]
Yes
