### ISSUE TITLE
We need to formalize a ‘provider’ interface

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/trueblocks-core#700]
Is there any way to set custom node URL or change Infura API key for EthSlurp util?

**User**
I am using EthSlurp, but looks like it stuck on run last times. I think this problem is connected with Infura restrictions. How can I change Infura node to my custom node or change Infura API key?
_[Note: The user should have said EtherScan everywhere in the above]_

**Me:**
EthSlurp doesn’t use Infura, it uses EtherScan. Do you have an API key for Infura or EtherScan? If EtherScan, then you need to go to EtherScan to get an API key. Here: https://etherscan.io/myapikey Please let me know if that works by posting to this issue.

**User**
I have read this issue before, so I thought that it uses Infura + EtherScan. I know how to receive EtherScan API key but how can I set my custom API key in the ethSlurp configuration?

**Me:**
There's a link here to get an API key or EtherScan https://etherscan.io/apis

**Comment by tjayrush** [comment]
getGlobalCurlContext()->provider is not documented

**Comment by wildmolasses** [comment]
This is one of a few places where a config file would be helpful. If quickblocks knew to read the rpc provider url from, say, ~/.quickBlocks/config.yml, then we could train the user to go to config.yml to change user parameters. Another example is the etherscan api key. There is also room to configure directory paths. There are some places around the code where a configurable directory path would make sense. Then we could remove the references to /Volumes/Samsung_T3.

**Comment by tjayrush** [comment]
Totally agree. Related: #892

**Comment by tjayrush** [comment]
I'm going to close this issue as it has been moved forward (if not resolved) by the recent PR.

**Comment by tjayrush** [comment]
I'm going to re-open this issue so we can discuss it at some point.

**Comment by tjayrush** [comment]
Now taken care of by rpcProvider option in config file.
