### ISSUE TITLE
un-getemize doTesting

### ISSUE THREAD

**Issue by wildmolasses** [Great-Hill-Corporation/trueblocks-core#880]
#1:

make install puts code in /usr/local/qblocks
puts /usr/local/qblocks/bin in PATH
developing, put pwd of repo's ./bin folder in PATH
is this a problem for developers only? are users fine with PATH change? Are developers fine adding their working dir to path?

----

shell scripts
doTesting: has to be run from the build folder
has to find out where the top of the quickblocks folder is (first 2 lines)
should remove working folder tests, but doesn't want to remove the .gitignore. Wants to remove only text files with underscore (?)
then does cmake, make, and make test
`doTesting tools/getBlock` will test just a folder
copies working to compare in a way that .gitignores get left behind. makes a nicer compare.
when testing a single tool, the test_results gets put in a wrong place (build/tools/getBlock/test_results)

difftest:
colordiff errors

doTestingAll: includes special tests (slow tests).
special tests defined in CMakeLists for each tool/etc.
CMakeLists on ../src defines the segregation rules.
This is how we could have different test suites (light node, infura, tracing, archive, etc.)

**Comment by tjayrush** [comment]
Maybe the best way to proceed here is to figure out what parts are essential (maybe color printing is not, but it would be nice to have if colordiff exists on the user's machine) and then incorporate that into the CMakeLists.txt file.

So then, users can just do:

    make test

and get whatever benefits `doTesting` brings (if any). See also #891

**Comment by tjayrush** [comment]
I don't think we have to do this. Instead, I think I will make the testing more 'data based.'  I this way, we can run testing against various different scenerios including the API. Closing.
