### ISSUE TITLE
blockScrape: gasAllowed vs gasUsed documentation error

### ISSUE THREAD

**Issue by mrns** [Great-Hill-Corporation/trueblocks-core#979]
The [QuickBlocks Documentation.pdf](https://github.com/Great-Hill-Corporation/quickBlocks/blob/master/docs/QuickBlocks%20Documentation.pdf) file has a small error in the blockScrape application section, when describing the internals of determining if a transaction was succesful.

Actual:
"If gasAllowed is smaller than gasUsed, the    
transaction unequivocally succeeded and is    
marked as such."

Expected:
"If gasAllowed is strictly greater than gasUsed, the    
transaction unequivocally succeeded and is    
marked as such."

**Comment by tjayrush** [comment]
When we make our next major release (i.e. v 1.0.0) this will be resolved. Thanks.
