### ISSUE TITLE
scraper.py: should fail more clearly

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/trueblocks-core#988]
Scraper.py should not continue to run if one of it's tools fails. To reproduce:

1) delete ../bin/blockScrape
2) run scraper.py

It will report the failure and continue to run. It should fail completely.

**Comment by wildmolasses** [comment]
Should also hedge against the user not running a tracing node

**Comment by tjayrush** [comment]
Can you fix this as part of fixing the scraper.py script (ungetmize)

The tools themselves will fail if parity is not running --tracing, but I'm not sure how to tell without asking Parity.

**Comment by tjayrush** [comment]
Scraper.py has long since disappeared.
